### PR TITLE
Added possibility to register a name for the Nats.Client

### PR DESCRIPTION
**Pull request by mceaglens**
Hi, 
Added parameter name to Nats.Client.start and start_link to set a registered process name on the
started connection.

### CODE REVIEW

**Comment by mceaglens** [comment]
Any comments?

**Comment by mceaglens** [comment]
@mcqueary, could you decide on merge or not? Or give some feedback?
Thanks.

**Comment by mceaglens** [comment]
Comments?
@camros?

**Comment by pavlenkoms** [comment]
why nobody care @camros?

**Pull request merged**
