### PR TITLE
Dry up tests

### PR DESCRIPTION
**Pull request by mindreframer**

### CODE REVIEW

**Comment by camros** [comment]
Thanks @mindreframer. Do you have a fix for that macro? If so and tests pass, will merge.

**Comment by mindreframer** [comment]
@camros It was due to a regression bug in Elixir 1.2.0... I bumped it up to v.1.2.1 on travis and it works. Not sure if this is an acceptable solution, but most projects in Elixir upgrade the Elixir version quite fast (it's mostly painless).

**Comment by camros** [comment]
Thanks. I think we should update the elixir version ref in mix.exs to 1.2.1 in case anyone builds / tests from source. Thoughts?

**Comment by mindreframer** [comment]
Yes, that would probably prevent some confusion later.

+1

On Mon, Feb 1, 2016 at 4:50 PM, Jeff Marshall <notifications@github.com>
wrote:

> Thanks. I think we should update the elixir version ref in mix.exs to
> 1.2.1 in case anyone builds / tests from source. Thoughts?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nats-io/elixir-nats/pull/20#issuecomment-178037407>.
>



-- 
------------------------------
  Roman Heinrich

  Email roman.heinrich@gmail.com
  Github github.com/mindreframer
  Twitter @mindreframer
  Blog devopsbox.es
  Xing xing.to/mindreframer
  Linkedin de.linkedin.com/in/mindreframer
  Resume devopsbox.es/resume/resume.html
  Delicious delicious.com/mindreframer
  Skype mindreframer

**Comment by camros** [comment]
@mindreframer i tried merging in your change but your tests still fail for me see #21 or the pr20 branch.

**Pull request closed without merging**
